services:
  - type: web
    name: bot_arena_hrv
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: ARENA_EMAIL
        sync: false
      - key: ARENA_PASSWORD
        sync: false
      - key: MY_SECRET_KEY
        sync: false
